### ISSUE TITLE
$ jekyll serve error

### ISSUE THREAD

**Issue by mategvo** [crispab/crisp-dna#43]
Running
`jekyll serve`
I am getting an error: 
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!': You have already activated json 2.0.4, but your Gemfile requires json 1.8.6. Since json is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports json as a default gem. (Gem::LoadError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

I don't have ruby experience - how can I fix this?

**Comment by mategvo** [comment]
I managed to run the site with 
`bundle exec jekyll serve`
